esp_toml_version = 1.0
firmware_images_url = "https://dl.espressif.com/AE/esp-dev-kits/"

supported_apps = ["usb_otg_fac_1_0_2", "lcd_ev_subboard2_480_480_v1_0", "lcd_ev_subboard3_800_480_v1_0"]

[usb_otg_fac_1_0_2]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "usb_otg_fac_1_0_2.bin"
android_app_url = ""
ios_app_url = ""

[lcd_ev_subboard2_480_480_v1_0]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "lcd_ev_subboard2_480_480_v1_0.bin"
android_app_url = ""
ios_app_url = ""

[lcd_ev_subboard3_800_480_v1_0]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "lcd_ev_subboard3_800_480_v1_0.bin"
android_app_url = ""
ios_app_url = ""
